/*
    CREATE USER [USER NAME] IDENTIFIED BT [PASSWORD]
    
*/

CREATE USER STU IDENTIFIED BY LOVE;
ALTER USER STU IDENTIFIED BY HOPE;
--DROP USER STU; ªË¡¶

GRANT CREATE SESSION TO STU;
GRANT SELECT ON SCOTT.sal_tcl TO STU;
GRANT INSERT ON SCOTT.sal_tcl TO STU;

REVOKE SELECT,INSERT ON SCOTT.SAL_TCL FROM STU;

SELECT * FROM USER_SYS_PRIVS;

CREATE ROLE SCHOOL;
GRANT CONNECT,RESOURCE,CREATE VIEW TO SCHOOL;

GRANT SCHOOL TO STU;

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE='SCHOOL';

