/*
FUNCTION 함수
TO_CHAR,TO_DATE,SYSDATE => 내장함수
사용자 정의 함수 (USER DEFINED FUNCTION)
특정한 기능을 모듈화, 재사용 용이 쿼리문을 간결하게 해줌,
CREATE OR REPLACE FUNCTION 함수명
[EXCEPTION]
RETURN 변수/값; 필수
END;
*/
--CREATE OR REPLACE FUNCTION FN_GET_DEPT_NAME (P_DEPTNO IN NUMBER)
--RETURN VARCHAR2
--IS
--    V_DEPTNAME DEPT.DNAME%TYPE;
--BEGIN
--    SELECT DNAME INTO V_DEPTNAME
--    FROM DEPT
--    WHERE DEPTNO=P_DEPTNO;
--    RETURN V_DEPTNAME;
--END;
--
--SELECT FN_GET_DEPT_NAME(20) FROM DUAL; --DUAL 데이터 내부 함수
--SELECT EMPNO,ENAME,DEPTNO,FN_GET_DEPT_NAME(DEPTNO) FROM EMP;


CREATE OR REPLACE FUNCTION FN_GET_DEPT_NAME (P_DEPTNO IN NUMBER)
RETURN VARCHAR2
IS
    V_DEPTNAME DEPT.DNAME%TYPE;
BEGIN
    SELECT DNAME INTO V_DEPTNAME
    FROM DEPT
    WHERE DEPTNO=P_DEPTNO;
    RETURN V_DEPTNAME;
END;
/

SELECT FN_GET_DEPT_NAME(20) FROM DUAL;

SELECT EMPNO,ENAME,DEPTNO,FN_GET_DEPT_NAME(DEPTNO) FROM EMP;
/

INSERT INTO EMP_TRIG(EMPNO)
VALUES(7777);
UPDATE EMP_TRIG SET ENAME='EEKEK' WHERE EMPNO=7777;

DELETE FROM EMP_TRIG WHERE EMPNO=7777;

SELECT * FROM EMP_TRIG;

SELECT * FROM EMP_LOG;












