--JOIN

SELECT * FROM DEPT;
SELECT * FROM EMP;
SELECT * FROM EMP a CROSS JOIN DEPT b ORDER BY EMPNO;

SELECT * FROM EMP E INNER JOIN DEPT D ON E.DEPTNO=D.DEPTNO WHERE E.JOB='CRERK';
SELECT * FROM EMP A CROSS JOIN DEPT B;
--INNER JOIN
SELECT * FROM EMP E INNER JOIN DEPT D ON E.DEPTNO=D.DEPTNO WHERE E.JOB='CLERK';


SELECT E.EMPNO,E.ENAME,E.JOB,D.DNAME FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND E.JOB='CLERK';

SELECT E.*,D.* FROM EMP E FULL OUTER JOIN DEPT D ON E.DEPTNO=D.DEPTNO;

SELECT E.*,D.* FROM EMP E LEFT OUTER JOIN DEPT D ON E.DEPTNO=D.DEPTNO;

--RIGHT OUTER JOIN
SELECT E.*,D.*
FROM EMP E RIGHT OUTER JOIN DEPT D ON E.DEPTNO=D.DEPTNO;

SELECT E.*,D.* FROM EMP E,DEPT D WHERE E.DEPTNO(+)=D.DEPTNO;

SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT A.EMPNO,A.ENAME,A.JOB,A.MGR,D.DEPTNO,D.DNAME,B.EMPNO,B.ENAME,B.JOB
FROM EMP A,EMP B, DEPT D
WHERE A.DEPTNO=D.DEPTNO -- 기준으로 연결
AND A.MGR=B.EMPNO; --관리자가 있는 사원들

SELECT A.EMPNO, A.ENAME, A.JOB, A.MGR, D.DEPTNO, D.DNAME, B.EMPNO, B.ENAME, B.JOB
FROM EMP A
INNER JOIN EMP B ON A.MGR = B.EMPNO
INNER JOIN DEPT D ON A.DEPTNO = D.DEPTNO;

SELECT E.ENAME,(SELECT D.DNAME FROM DEPT D WHERE D.DEPTNO=E.DEPTNO) AS DEPTNAME
FROM EMP E
WHERE E.JOB='MANAGER';

--FROM INLINE VIEW
SELECT EMP_NAME,SALARY FROM(SELECT E.ENAME AS EMP_NAME, E.SAL AS SALARY 
FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND D.DNAME='SALES') 
WHERE SALARY BETWEEN 1000 AND 2000;

SELECT E.ENAME AS EMP_NAME,E.SAL AS SALARY FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND D.DNAME='SALES';

--WHERE 행과 무관하게 단일 컬럼으로 리턴
SELECT * FROM DEPT D
WHERE D.DEPTNO IN(SELECT E.DEPTNO FROM EMP E WHERE E.SAL>3000);

SELECT ENAME,SAL FROM EMP
WHERE SAL>(SELECT AVG(SAL) FROM EMP);


SELECT d.DNAME AS department_name, mgr.ENAME AS manager_name, mgr.SAL AS manager_salary,
       COUNT(emp.EMPNO) AS employee_count, AVG(emp.SAL) AS average_salary
FROM EMP emp
INNER JOIN DEPT d ON emp.DEPTNO = d.DEPTNO
INNER JOIN EMP mgr ON emp.MGR = mgr.EMPNO
GROUP BY d.DNAME, mgr.ENAME, mgr.JOB, mgr.SAL;



select d.deptno,d.dname, e.empno, e.ename, e.sal
from dept d join emp e on d.deptno=e.deptno
where (d.deptno,e.sal) in 
(select deptno,min(sal) from emp group by deptno);

SELECT D.DNAME
FROM DEPT D
WHERE EXISTS(SELECT E.ENAME
            FROM EMP E
            WHERE E.DEPTNO=D.DEPTNO
            AND E.SAL>3000);
            
--Q1 부서코드 부서이름 사원번호 사원명 봉급을 보여주는데 
-- 사원의 봉급이 2000초과인 사원만

--Q2 부서별 
--부서코드 부서명 급여평균 최대급여 최소급여 부서인원수 

SELECT D.DEPTNO, D.DNAME, AVG(E.SAL),MAX(E.SAL),MIN(E.SAL),COUNT(*)
FROM EMP E FULL OUTER JOIN DEPT D ON E.DEPTNO=D.DEPTNO 
WHERE E.SAL IS NOT NULL
GROUP BY D.DEPTNO,D.DNAME;




SELECT EMP.*, DEPT.DNAME
FROM EMP
FULL OUTER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;



SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT D.DEPTNO,D.DNAME,E.EMPNO,E.ENAME,E.SAL 
FROM EMP E
FULL OUTER JOIN DEPT D ON E.DEPTNO=D.DEPTNO WHERE SAL>2000;


SELECT EMP.*, DEPT.DNAME,DEPT.LOC
FROM EMP
FULL OUTER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

--1번 문제
SELECT E.EMPNO,E.ENAME,E.DEPTNO,D.DNAME
FROM EMP E
LEFT JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
ORDER BY E.ENAME;

--2번 문제
SELECT E.EMPNO,E.ENAME,E.SAL,D.DNAME
FROM EMP E
LEFT JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE E.SAL>=2000
ORDER BY E.ENAME;

--3번 문제
SELECT E.EMPNO,E.ENAME,E.JOB,E.SAL,D.DNAME
FROM EMP E
LEFT JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE E.JOB='MANAGER' AND SAL>=2500
ORDER BY E.ENAME;

--4번 문제
SELECT E.EMPNO,E.ENAME,E.SAL,L.GRADE
FROM EMP E
LEFT JOIN SALGRADE L
ON E.SAL BETWEEN L.LOSAL AND L.HISAL
ORDER BY L.GRADE DESC;

--확인용
SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT * FROM SALGRADE;

--5번 문제
SELECT E.EMPNO,E.ENAME,D.DNAME,E.SAL,L.GRADE
FROM EMP E
LEFT JOIN SALGRADE L
ON E.SAL BETWEEN L.LOSAL AND L.HISAL
LEFT JOIN DEPT D
ON E.DEPTNO=D.DEPTNO
ORDER BY L.GRADE DESC;

--6번 문제
SELECT ENAME,MGR FROM EMP;

--7번 문제
SELECT E1.ENAME,E2.ENAME MGR,E3.ENAME GREND_MGR
FROM EMP E1 LEFT JOIN EMP E2 ON E1.MGR=E2.EMPNO
LEFT JOIN EMP E3 ON E2.MGR=E3.EMPNO;

--8번 문제
SELECT E1.ENAME,(
CASE 
WHEN E2.ENAME IS NULL THEN E1.ENAME 
ELSE E2.ENAME 
END) MGR,(
CASE 
WHEN E2.MGR IS NULL THEN E1.ENAME
WHEN E1.MGR IS NULL THEN E2.ENAME 
ELSE E3.ENAME
END) GREND_MGR
FROM EMP E1 LEFT JOIN EMP E2 ON E1.MGR=E2.EMPNO
LEFT JOIN EMP E3 ON E2.MGR=E3.EMPNO;

SELECT EA.ENAME, EB.ENAME 상사,EC.ENAME 다음_상사
FROM EMP EA JOIN EMP EB ON EA.MGR=EB.EMPNO JOIN EMP EC ON EB.MGR=EC.EMPNO;







