--JOIN

SELECT * FROM DEPT;
SELECT * FROM EMP;
SELECT * FROM EMP a CROSS JOIN DEPT b ORDER BY EMPNO;

SELECT * FROM EMP E INNER JOIN DEPT D ON E.DEPTNO=D.DEPTNO WHERE E.JOB='CRERK';
SELECT * FROM EMP A CROSS JOIN DEPT B;
--INNER JOIN
SELECT * FROM EMP E INNER JOIN DEPT D ON E.DEPTNO=D.DEPTNO WHERE E.JOB='CLERK';


SELECT E.EMPNO,E.ENAME,E.JOB,D.DNAME FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND E.JOB='CLERK';

SELECT E.*,D.* FROM EMP E FULL OUTER JOIN DEPT D ON E.DEPTNO=D.DEPTNO;

SELECT E.*,D.* FROM EMP E LEFT OUTER JOIN DEPT D ON E.DEPTNO=D.DEPTNO;

--RIGHT OUTER JOIN
SELECT E.*,D.*
FROM EMP E RIGHT OUTER JOIN DEPT D ON E.DEPTNO=D.DEPTNO;

SELECT E.*,D.* FROM EMP E,DEPT D WHERE E.DEPTNO(+)=D.DEPTNO;

SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT A.EMPNO,A.ENAME,A.JOB,A.MGR,D.DEPTNO,D.DNAME,B.EMPNO,B.ENAME,B.JOB
FROM EMP A,EMP B, DEPT D
WHERE A.DEPTNO=D.DEPTNO -- 기준으로 연결
AND A.MGR=B.EMPNO; --관리자가 있는 사원들

SELECT A.EMPNO, A.ENAME, A.JOB, A.MGR, D.DEPTNO, D.DNAME, B.EMPNO, B.ENAME, B.JOB
FROM EMP A
INNER JOIN EMP B ON A.MGR = B.EMPNO
INNER JOIN DEPT D ON A.DEPTNO = D.DEPTNO;

SELECT E.ENAME,(SELECT D.DNAME FROM DEPT D WHERE D.DEPTNO=E.DEPTNO) AS DEPTNAME
FROM EMP E
WHERE E.JOB='MANAGER';

--FROM INLINE VIEW
SELECT EMP_NAME,SALARY FROM(SELECT E.ENAME AS EMP_NAME, E.SAL AS SALARY 
FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND D.DNAME='SALES') 
WHERE SALARY BETWEEN 1000 AND 2000;

SELECT E.ENAME AS EMP_NAME,E.SAL AS SALARY FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND D.DNAME='SALES';

--WHERE 행과 무관하게 단일 컬럼으로 리턴
SELECT * FROM DEPT D
WHERE D.DEPTNO IN(SELECT E.DEPTNO FROM EMP E WHERE E.SAL>3000);

SELECT ENAME,SAL FROM EMP
WHERE SAL>(SELECT AVG(SAL) FROM EMP);


SELECT d.DNAME AS department_name, mgr.ENAME AS manager_name, mgr.SAL AS manager_salary,
       COUNT(emp.EMPNO) AS employee_count, AVG(emp.SAL) AS average_salary
FROM EMP emp
INNER JOIN DEPT d ON emp.DEPTNO = d.DEPTNO
INNER JOIN EMP mgr ON emp.MGR = mgr.EMPNO
GROUP BY d.DNAME, mgr.ENAME, mgr.JOB, mgr.SAL;



select d.deptno,d.dname, e.empno, e.ename, e.sal
from dept d join emp e on d.deptno=e.deptno
where (d.deptno,e.sal) in 
(select deptno,min(sal) from emp group by deptno);

SELECT D.DNAME
FROM DEPT D
WHERE EXISTS(SELECT E.ENAME
            FROM EMP E
            WHERE E.DEPTNO=D.DEPTNO
            AND E.SAL>3000);
            
--Q1 부서코드 부서이름 사원번호 사원명 봉급을 보여주는데 
-- 사원의 봉급이 2000초과인 사원만

--Q2 부서별 
--부서코드 부서명 급여평균 최대급여 최소급여 부서인원수 

SELECT * FROM EMP;

SELECT D.DEPTNO, D.DNAME, AVG(E.SAL),MAX(E.SAL),MIN(E.SAL),COUNT(*)
FROM EMP E 
FULL OUTER JOIN DEPT D ON E.DEPTNO=D.DEPTNO 
GROUP BY D.DEPTNO,D.DNAME;

--Q3 부서별 고용인의 정보
--부서코드 부서명 사원번호 이름 직급 봉급
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, JOB, SAL FROM EMP E
RIGHT JOIN DEPT D ON E.DEPTNO=D.DEPTNO;

SELECT d.DEPTNO ,d.DNAME, e.EMPNO ,e.ENAME ,JOB ,SAL FROM emp e,dept d where e.DEPTNO =d.DEPTNO;


SELECT * FROM EMP;
SELECT * FROM SALGRADE;
--Q4 부서별
--부서코드 부서명 사번 사원명 관리자사번 관리자명
-- 해당사원의급여등급 등급최저급여 등급최고급여
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.MGR, E2.ENAME, S.GRADE, S.LOSAL, S.HISAL FROM EMP E
LEFT JOIN EMP E2 ON E.MGR=E2.EMPNO
RIGHT JOIN DEPT D ON E.DEPTNO=D.DEPTNO
LEFT JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
ORDER BY D.DEPTNO;

SELECT * FROM EMP E
FULL JOIN EMP E2 ON E.MGR=E2.EMPNO;

UPDATE EMP SET SAL=1900 WHERE EMPNO=7701;

SELECT E.EMPNO,E.ENAME,E.DEPTNO,D.DNAME,D.LOC
FROM (SELECT * FROM EMP WHERE DEPTNO=10) E,(SELECT * FROM DEPT) D
WHERE E.DEPTNO=D.DEPTNO;

WITH
E AS (SELECT * FROM EMP WHERE DEPTNO=10),
D AS (SELECT * FROM DEPT)
SELECT E.EMPNO,E.ENAME,E.DEPTNO,D.DNAME,D.LOC
FROM E,D
WHERE E.DEPTNO=D.DEPTNO;

--Q1 ALLEN 사원의 직급과 동일한 사원들의
--직급 사번 사원명 봉급 부서코드 부서명
SELECT E.JOB, E.EMPNO, E.ENAME, E.SAL, D.DEPTNO, D.DNAME FROM EMP E
LEFT JOIN DEPT D ON E.DEPTNO=D.DEPTNO
WHERE E.JOB=(SELECT JOB FROM EMP WHERE ENAME='ALLEN');

SELECT * FROM EMP;
--Q2 전체 평균 급여보다 많이 받는 사원의
--사번 사원 명 입사일(YYYY-MM-DD) 부서명 부서위치 급여 급여 등급
SELECT E.EMPNO, E.ENAME, TO_CHAR(E.HIREDATE,'YYYY-MM-DD'), D.DNAME, D.LOC, E.SAL, S.GRADE FROM EMP E
LEFT JOIN DEPT D ON E.DEPTNO=D.DEPTNO
LEFT JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
ORDER BY E.SAL DESC, E.ENAME;




--Q3 10번 부서의 인원 중 30번 부서에 없는 직급을 가진 직원의
--사번 사원명 직급 부서코드 부서명 부서위치
SELECT E.EMPNO, E.ENAME, E.JOB, D.DEPTNO, D.DNAME, D.LOC FROM EMP E
LEFT JOIN DEPT D ON E.DEPTNO=D.DEPTNO
WHERE E.DEPTNO = 10 AND E.JOB NOT IN(SELECT JOB FROM EMP WHERE DEPTNO=30);


SELECT E.EMPNO , E.ENAME , E.JOB,E.DEPTNO,D.DNAME,D.LOC FROM EMP E,DEPT D
WHERE E.DEPTNO=D.DEPTNO AND E.DEPTNO=10 AND E.JOB IN (SELECT E.JOB FROM EMP E WHERE E.DEPTNO=30);


--Q4 SALESMAN의 최대급여보다 많이 급여를 받는 사람들의
--사번 사원명 급여 급여등급
SELECT DISTINCT JOB FROM EMP WHERE DEPTNO=30;

SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE FROM EMP E
LEFT JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
WHERE E.SAL> (SELECT MAX(SAL) FROM EMP WHERE JOB='SALESMAN');

SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE FROM EMP E
LEFT JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
WHERE E.SAL>ALL(SELECT SAL FROM EMP WHERE JOB='SALESMAN');


SELECT EMP.*, DEPT.DNAME
FROM EMP
FULL OUTER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;



SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT D.DEPTNO,D.DNAME,E.EMPNO,E.ENAME,E.SAL 
FROM EMP E
FULL OUTER JOIN DEPT D ON E.DEPTNO=D.DEPTNO WHERE SAL>2000;


SELECT EMP.*, DEPT.DNAME,DEPT.LOC
FROM EMP
FULL OUTER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

--1번 문제
SELECT E.EMPNO,E.ENAME,E.DEPTNO,D.DNAME
FROM EMP E
LEFT JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
ORDER BY E.ENAME;

--2번 문제
SELECT E.EMPNO,E.ENAME,E.SAL,D.DNAME
FROM EMP E
LEFT JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE E.SAL>=2000
ORDER BY E.ENAME;

--3번 문제
SELECT E.EMPNO,E.ENAME,E.JOB,E.SAL,D.DNAME
FROM EMP E
LEFT JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE E.JOB='MANAGER' AND SAL>=2500
ORDER BY E.ENAME;

--4번 문제
SELECT E.EMPNO,E.ENAME,E.SAL,L.GRADE
FROM EMP E
LEFT JOIN SALGRADE L
ON E.SAL BETWEEN L.LOSAL AND L.HISAL
ORDER BY L.GRADE DESC;

--확인용
SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT * FROM SALGRADE;

--5번 문제
SELECT E.EMPNO,E.ENAME,D.DNAME,E.SAL,L.GRADE
FROM EMP E
LEFT JOIN SALGRADE L
ON E.SAL BETWEEN L.LOSAL AND L.HISAL
LEFT JOIN DEPT D
ON E.DEPTNO=D.DEPTNO
ORDER BY L.GRADE DESC;

--6번 문제
SELECT ENAME,MGR FROM EMP;

--7번 문제
SELECT E1.ENAME,E2.ENAME MGR,E3.ENAME GREND_MGR
FROM EMP E1 LEFT JOIN EMP E2 ON E1.MGR=E2.EMPNO
LEFT JOIN EMP E3 ON E2.MGR=E3.EMPNO;

--8번 문제
SELECT E1.ENAME,(
CASE 
WHEN E2.ENAME IS NULL THEN E1.ENAME 
ELSE E2.ENAME 
END) MGR,(
CASE 
WHEN E2.MGR IS NULL THEN E1.ENAME
WHEN E1.MGR IS NULL THEN E2.ENAME 
ELSE E3.ENAME
END) GREND_MGR
FROM EMP E1 LEFT JOIN EMP E2 ON E1.MGR=E2.EMPNO
LEFT JOIN EMP E3 ON E2.MGR=E3.EMPNO;




--확인용
SELECT * FROM EMP;
--서브쿼리 1번
SELECT EMPNO,ENAME,SAL FROM EMP WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME='BLAKE');

--2번
SELECT EMPNO,ENAME,HIREDATE FROM EMP WHERE HIREDATE>(SELECT HIREDATE FROM EMP WHERE ENAME='MILLER');

--3번
SELECT EMPNO,ENAME,SAL FROM EMP WHERE SAL>(SELECT AVG(SAL) FROM EMP);

--4번
SELECT EMPNO,ENAME,SAL FROM EMP WHERE 
DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='CLARK')
AND SAL>(SELECT SAL FROM EMP WHERE EMPNO=7698);

--5번
SELECT EMPNO,ENAME,JOB FROM EMP 
WHERE EMPNO=7844;

--6번
SELECT EMPNO,ENAME,JOB FROM EMP 
WHERE JOB=(SELECT JOB FROM EMP WHERE EMPNO=7844);

--7번
SELECT EMPNO,ENAME,JOB,SAL FROM EMP 
WHERE JOB=(SELECT JOB FROM EMP WHERE EMPNO=7521)
AND SAL>(SELECT SAL FROM EMP WHERE EMPNO=7521);

--8번
SELECT EMPNO,ENAME,SAL FROM EMP WHERE SAL=(SELECT MIN(SAL) FROM EMP);

--확인용
SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT DEPTNO, COUNT(*) FROM EMP 
GROUP BY DEPTNO;
--9번
SELECT DEPTNO, MIN(SAL) FROM EMP 
GROUP BY DEPTNO HAVING MIN(SAL)>
(SELECT MIN(SAL) FROM EMP GROUP BY DEPTNO HAVING DEPTNO=30);

--10번
SELECT D.DEPTNO,D.DNAME FROM EMP E
LEFT JOIN DEPT D ON E.DEPTNO=D.DEPTNO 
GROUP BY D.DEPTNO,D.DNAME HAVING COUNT(*)>=2;

--11번
SELECT E.DEPTNO,D.DNAME FROM EMP E 
LEFT JOIN DEPT D ON E.DEPTNO=D.DEPTNO WHERE JOB='CLERK';


--12번
SELECT E.DEPTNO,D.DNAME,E.EMPNO,E.ENAME,E.SAL FROM EMP E
LEFT JOIN DEPT D ON E.DEPTNO=D.DEPTNO WHERE SAL IN (
SELECT MIN(SAL) FROM EMP GROUP BY DEPTNO);

SELECT * FROM EMP;
--13번
SELECT E1.EMPNO 부하직원번호, E1.ENAME 부하직원이름, E1.MGR 직속상사번호, E2.ENAME 직속상사이름 FROM EMP E1
LEFT JOIN EMP E2 ON E1.MGR=E2.EMPNO;

--14번
SELECT E.EMPNO, E.ENAME, E.SAL FROM EMP E
WHERE E.SAL>=(SELECT AVG(SAL) FROM EMP) AND E.SAL<(SELECT MAX(SAL) FROM EMP);

--15번
SELECT E.EMPNO, E.ENAME, E.SAL FROM EMP E
WHERE ROWNUM <=5
ORDER BY E.SAL DESC;


















