/* CHAR FUNCTION
   UPPER LOWER INITCAP
*/

SELECT ENAME,UPPER(ENAME),LOWER(ENAME),INITCAP(ENAME) FROM EMP;
SELECT * FROM EMP WHERE LOWER (ENAME)='JAMES';

--길이 반환
SELECT ENAME,LENGTH(ENAME),SAL,LENGTH(SAL),LENGTH('한글'),LENGTHB('한글') FROM EMP;

--문자 자르는 규칙
SELECT JOB,SUBSTR(JOB,1,2),SUBSTR(JOB,3,2),SUBSTR(JOB,5), SUBSTR(JOB,-LENGTH(JOB)), SUBSTR(JOB,-LENGTH(JOB),2), SUBSTR(JOB,-3) FROM EMP;


--문자 찾는 함수 INSTR()
SELECT INSTR('HELLO, ORACLE', 'L') INS1 
,INSTR('HELLO, ORACLE', 'L',5) INS2
,INSTR('HELLO, ORACLE', 'L',2,2) INS3 FROM DUAL;

SELECT JOB, INSTR(JOB,'A',1,2)
FROM EMP
WHERE INSTR(JOB,'A')>0;
--LIKE로 같은 효과
SELECT JOB, INSTR(JOB,'A',1,2)
FROM EMP
WHERE JOB LIKE '%A%';

SELECT * FROM EMP E
RIGHT JOIN DEPT D ON E.DEPTNO=D.DEPTNO;
